final data = [
  {
    "id": "GEN-001",
    "reference": "GEN-001",
    "terminologie": "Chiffres clés",
    "intitule": "Superficie des plantations industrielles CI",
    "type": "Primaire",
    "unite": "Ha",
    "definition":
        "Surface en hectares des surfaces de plantation industrielles",
    "processus": ["Agricole / Plantation"],
    "gri": "2-6",
    "odd": 13,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "0",
    "id_enjeu": "0",
    "frequence": 12,
    "numero": 1
  },
  {
    "id": "GEN-002",
    "reference": "GEN-002",
    "terminologie": "Chiffres clés",
    "intitule": "Superficie des plantations villageoises",
    "type": "Primaire",
    "unite": "Ha",
    "definition": "Surface en hectares des surfaces de plantation villageoises",
    "processus": ["Agricole / Plantation"],
    "gri": "2-6",
    "odd": 13,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "0",
    "id_enjeu": "0",
    "frequence": 12,
    "numero": 2
  },
  {
    "id": "GEN-003",
    "reference": "GEN-003",
    "terminologie": "Chiffres clés",
    "intitule": "Superficie totale des plantations",
    "type": "Calculé",
    "unite": "Ha",
    "definition":
        "Superficie des plantations industrielles + Superficie des plantations villageoises",
    "processus": ["Agricole / Plantation"],
    "gri": "2-6",
    "odd": 13,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "0",
    "id_enjeu": "0",
    "frequence": 12,
    "numero": 3
  },
  {
    "id": "GEN-004",
    "reference": "GEN-004",
    "terminologie": "Chiffres clés",
    "intitule": "Nombre de plantations villageoises",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Nombre total de plantations villageoises",
    "processus": ["Agricole / Plantation"],
    "gri": "2-6",
    "odd": 13,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "0",
    "id_enjeu": "0",
    "frequence": 12,
    "numero": 4
  },
  {
    "id": "GEN-005",
    "reference": "GEN-005",
    "terminologie": "Chiffres clés",
    "intitule": "Nombre de plantations villageoises géolocalisées",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Nombre de plantations villageoises géolocalisées",
    "processus": ["Agricole / Plantation"],
    "gri": "2-6",
    "odd": 13,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "0",
    "id_enjeu": "0",
    "frequence": 12,
    "numero": 5
  },
  {
    "id": "GEN-006",
    "reference": "GEN-006",
    "terminologie": "Chiffres clés",
    "intitule": "Taux de plantations villageoises géolocalisées",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Nombre de plantations géolocalisées / Nombre de plantations toale",
    "processus": ["Filiale"],
    "gri": "2-6",
    "odd": 13,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "0",
    "id_enjeu": "0",
    "frequence": 12,
    "numero": 6
  },
  {
    "id": "GOU1a-001",
    "reference": "GOU1a-001",
    "terminologie": "Système de gouvernance",
    "intitule": "Membres au Conseil d'Administration",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Membres du Conseil d'Administration",
    "processus": ["Direction Générale"],
    "gri": "2-9",
    "odd": 16,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-a",
    "frequence": 12,
    "numero": 7
  },
  {
    "id": "GOU1a-002",
    "reference": "GOU1a-002",
    "terminologie": "Système de gouvernance",
    "intitule": "Membres indépendants au Conseil d'Administration",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Membres du Conseil d'Administration qui n'ont pas de relation avec la société, sauf à titre d'administrateurs. Ils ne peuvent être parents des fondateurs, ne peuvent êttre des acteurs clés ou des employés clés de l'entreprise.",
    "processus": ["Direction Générale"],
    "gri": "2-9",
    "odd": 16,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-a",
    "frequence": 12,
    "numero": 8
  },
  {
    "id": "GOU1a-003",
    "reference": "GOU1a-003",
    "terminologie": "Système de gouvernance",
    "intitule": "Membres indépendants au Conseil d'Administration",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Total des Membres indépendants au Conseil d'Administration / Total des Membres au Conseil d'Administration",
    "processus": ["Direction Générale"],
    "gri": "2-9",
    "odd": 16,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-a",
    "frequence": 12,
    "numero": 9
  },
  {
    "id": "GOU1a-004",
    "reference": "GOU1a-004",
    "terminologie": "Système de gouvernance",
    "intitule": "Femmes dans le Conseil d'Administration",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Femmes administratrices au Conseil d'Administration",
    "processus": ["Direction Générale"],
    "gri": "2-9",
    "odd": 5,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-a",
    "frequence": 12,
    "numero": 10
  },
  {
    "id": "GOU1a-005",
    "reference": "GOU1a-005",
    "terminologie": "Système de gouvernance",
    "intitule": "Femmes dans le Conseil d'Administration",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Total des Femmes dans le Conseil d'Administration / Total des Membres au Conseil d'Administration",
    "processus": ["Direction Générale"],
    "gri": "2-9",
    "odd": 5,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-a",
    "frequence": 12,
    "numero": 11
  },
  {
    "id": "GOU1b-001",
    "reference": "GOU1b-001",
    "terminologie": "Conformité",
    "intitule":
        "Diagnostic menés pour détecter les non-conformités environnementales",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Audits menés sur les procédures pour détecter les non-conformités.",
    "processus": ["Developpement Durable"],
    "gri": "307-1",
    "odd": "12;13;14;15;6",
    "formule": "Somme",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-b",
    "frequence": 12,
    "numero": 12
  },
  {
    "id": "GOU1b-002",
    "reference": "GOU1b-002",
    "terminologie": "Conformité",
    "intitule":
        "Diagnostic menés pour détecter les non-conformités socio-économiques",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Audits menés sur les procédures pour détecter les non-conformités sociales concernant les travailleurs et la chaîne de valeur",
    "processus": ["Developpement Durable"],
    "gri": "419-1",
    "odd": "1;2;3;4;5;7;8;9;11",
    "formule": "Somme",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-b",
    "frequence": 12,
    "numero": 13
  },
  {
    "id": "GOU1b-003",
    "reference": "GOU1b-003",
    "terminologie": "Conformité",
    "intitule": "Total des diagnostics menés pour détecter les non-conformités",
    "type": "Calculé",
    "unite": "Nombre",
    "definition":
        "Total des Diagnostic menés pour détecter les non-conformités environnementales et des diagnostic menés pour détecter les non-conformités socio-économiques",
    "processus": ["Developpement Durable"],
    "gri": "419-1",
    "odd": "1;2;3;4;5;7;8;9;11",
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "1-b",
    "frequence": 12,
    "numero": 14
  },
  {
    "id": "GOU2-001",
    "reference": "GOU2-001",
    "terminologie": "Achats responsables",
    "intitule": "Achats de matières premières et emballages",
    "type": "Primaire",
    "unite": "KFCFA",
    "definition":
        "Achat de matières premières (lubrifiants pour les machines de production, pièces semi-finis, emballages, papiers)",
    "processus": ["Direction Achats"],
    "gri": "204-1",
    "odd": "12;16",
    "formule": "Somme",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "2",
    "frequence": 12,
    "numero": 15
  },
  {
    "id": "GOU2-002",
    "reference": "GOU2-002",
    "terminologie": "Achats responsables",
    "intitule": "Achats de prestations de services",
    "type": "Primaire",
    "unite": "KFCFA",
    "definition": "Achats de prestations de services",
    "processus": ["Direction Achats"],
    "gri": "204-1",
    "odd": "12;16",
    "formule": "Somme",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "2",
    "frequence": 12,
    "numero": 16
  },
  {
    "id": "GOU2-003",
    "reference": "GOU2-003",
    "terminologie": "Achats responsables",
    "intitule": "Total des Achats réalisés",
    "type": "Calculé",
    "unite": "KFCFA",
    "definition":
        "Total des achats de matières premières et emballages + services",
    "processus": ["Filiale"],
    "gri": "204-1",
    "odd": "12;16",
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "2",
    "frequence": 12,
    "numero": 17
  },
  {
    "id": "GOU2-004",
    "reference": "GOU2-004",
    "terminologie": "Achats responsables",
    "intitule": "% du chiffre d'affaires issus des achats réalisés",
    "type": "Calculé",
    "unite": "KFCFA",
    "definition": "Total des achats réalisé / Chiffre d'affaires",
    "processus": ["Filiale"],
    "gri": "204-1",
    "odd": "12;16",
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "2",
    "frequence": 12,
    "numero": 18
  },
  {
    "id": "GOU3-001",
    "reference": "GOU3-001",
    "terminologie": "Certification",
    "intitule":
        "Tonnage de production faisant l'objet d'une certification RSPO ou RSPO NPP",
    "type": "Primaire",
    "unite": "Tonnes",
    "definition":
        "Procédure RSPO pour le développement de nouvelles plantations\n(NPP)",
    "processus": ["Developpement Durable"],
    "gri": "204-1",
    "odd": 12,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "3",
    "frequence": 12,
    "numero": 19
  },
  {
    "id": "GOU3-002",
    "reference": "GOU3-002",
    "terminologie": "Certification",
    "intitule":
        "Part du tonnage faisant l'objet d'une certification RSPO ou RSPO NPP",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Tonnage de production faisant l'objet d'une certification RSPO / Tonnage total de production brute",
    "processus": ["Developpement Durable"],
    "gri": "204-1",
    "odd": 12,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "3",
    "frequence": 12,
    "numero": 20
  },
  {
    "id": "GOU3-003",
    "reference": "GOU3-003",
    "terminologie": "Certification",
    "intitule":
        "Tonnage de production faisant l'objet d'une certification en matière de traçabilité",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "FSSC 22000-4.1, ISCC, GlobalGAP, Fairtrade, UTZ, RA, FSC, SNR-I, GPSNR, ISO et autres certifications",
    "processus": ["Developpement Durable"],
    "gri": "204-1",
    "odd": 12,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "3",
    "frequence": 12,
    "numero": 21
  },
  {
    "id": "GOU3-004",
    "reference": "GOU3-004",
    "terminologie": "Certification",
    "intitule":
        "Part du tonnage faisant l'objet d'une certification en matière de traçabilité",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Tonnage faisant l'objet d'une traçabilité / Tonnage total de production",
    "processus": ["Developpement Durable"],
    "gri": "204-1",
    "odd": 12,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "3",
    "frequence": 12,
    "numero": 22
  },
  {
    "id": "GOU3-005",
    "reference": "GOU3-005",
    "terminologie": "Certification",
    "intitule": "Sites certifiés ISO 14001",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Sites certifiés ISO 14001",
    "processus": ["Developpement Durable"],
    "gri": "307-1",
    "odd": 12,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "3",
    "frequence": 12,
    "numero": 23
  },
  {
    "id": "GOU3-006",
    "reference": "GOU3-006",
    "terminologie": "Certification",
    "intitule": "Part des sites certifiés ISO 14001",
    "type": "Calculé",
    "unite": "%",
    "definition": "Sites certifiés ISO 14001 / Total des sites de production",
    "processus": ["Developpement Durable"],
    "gri": "307-1",
    "odd": 12,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "1",
    "id_enjeu": "3",
    "frequence": 12,
    "numero": 24
  },
  {
    "id": "EMP4-001",
    "reference": "EMP4-001",
    "terminologie": "Emploi",
    "intitule": "Collaborateurs avec un contrat à durée indéterminée",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Collaborateurs à la fin d'année de reporting ayant un contrat de travail à durée indéterminée, pour un travail à temps plein ou à temps partiel.",
    "processus": ["Ressources Humaines"],
    "gri": "401-1",
    "odd": 8,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "4",
    "frequence": 12,
    "numero": 25
  },
  {
    "id": "EMP4-002",
    "reference": "EMP4-002",
    "terminologie": "Emploi",
    "intitule": "Collaborateurs avec un contrat à durée déterminée",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Collaborateurs à la fin d'année ayant un contrat de travail, pour un travail à temps plein ou à temps partiel, qui prend fin à l'expiration d'une période déterminée ou à l'achèvement d'une tâche spécifique.",
    "processus": ["Ressources Humaines"],
    "gri": "401-1",
    "odd": 8,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "4",
    "frequence": 12,
    "numero": 26
  },
  {
    "id": "EMP4-003",
    "reference": "EMP4-003",
    "terminologie": "Chiffres clés",
    "intitule": "Total des collaborateurs",
    "type": "Calculé",
    "unite": "Nombre",
    "definition": "Total des collaborateurs",
    "processus": ["Ressources Humaines"],
    "gri": "2-8",
    "odd": 8,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "4",
    "frequence": 12,
    "numero": 27
  },
  {
    "id": "EMP4-004",
    "reference": "EMP4-004",
    "terminologie": "Emploi",
    "intitule":
        "Part des collaborateurs possédant un contrat à durée indéterminée",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Total des collaborateurs avec un contrat de travail à durée indéterminée / Total des collaborateurs",
    "processus": ["Ressources Humaines"],
    "gri": "401-1",
    "odd": 8,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "4",
    "frequence": 12,
    "numero": 28
  },
  {
    "id": "EMP5-001",
    "reference": "EMP5-001",
    "terminologie": "Santé et Sécurité",
    "intitule": "Absence liés aux maladies professionnelles",
    "type": "Primaire",
    "unite": "Jours",
    "definition":
        "Maladie contractée principalement à la suite d'une exposition à des facteurs de risque découlant de l'activité professionnelle.",
    "processus": ["Médecin"],
    "gri": "403-10",
    "odd": 3,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "5",
    "frequence": 12,
    "numero": 29
  },
  {
    "id": "EMP5-002",
    "reference": "EMP5-002",
    "terminologie": "Santé et Sécurité",
    "intitule":
        "Collaborateurs ayant déclaré une maladie professionnelle déclarées durant l'année de reporting",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Collaborateurs ayant déclaré une maladie professionnelle déclarées durant l'année de reporting",
    "processus": ["Médecin"],
    "gri": "403-10",
    "odd": 3,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "5",
    "frequence": 12,
    "numero": 30
  },
  {
    "id": "EMP5-003",
    "reference": "EMP5-003",
    "terminologie": "Santé et Sécurité",
    "intitule":
        "Collaborateurs sensibilisés et formés aux normes de santé et sécurité au travail",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Collaborateurs évalués concernant la santé et sécurité au travail",
    "processus": ["Developpement Durable"],
    "gri": "403-4",
    "odd": 3,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "5",
    "frequence": 12,
    "numero": 31
  },
  {
    "id": "EMP5-004",
    "reference": "EMP5-004",
    "terminologie": "Santé et Sécurité",
    "intitule":
        "Part des collaborateurs sensibilisés et formés aux normes de santé et sécurité au travail",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Total des collaborateurs sensibilisés et formés aux normes de santé et sécurité au travail /  Total des Collaborateurs",
    "processus": ["Developpement Durable"],
    "gri": "403-4",
    "odd": 3,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "5",
    "frequence": 12,
    "numero": 32
  },
  {
    "id": "EMP6-001",
    "reference": "EMP6-001",
    "terminologie": "Cadre de vie",
    "intitule": "Logements existants",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Nombre de logements existant mis à la disposition des collaborateurs",
    "processus": ["Infrastructures"],
    "gri": "401-2",
    "odd": 8,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "6",
    "frequence": 12,
    "numero": 33
  },
  {
    "id": "EMP6-002",
    "reference": "EMP6-002",
    "terminologie": "Cadre de vie",
    "intitule": "Collaborateurs bénéficiant d'un logement",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Collaborateurs permanents bénéficiant d'un logement",
    "processus": ["Ressources Humaines"],
    "gri": "401-2",
    "odd": 8,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "6",
    "frequence": 12,
    "numero": 34
  },
  {
    "id": "EMP6-003",
    "reference": "EMP6-003",
    "terminologie": "Cadre de vie",
    "intitule":
        "Personnes vivant dans les logements en dehors des collaborateurs",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Personnes vivant dans les logements en dehors des collaborateurs",
    "processus": ["Ressources Humaines"],
    "gri": "401-2",
    "odd": 8,
    "formule": "Dernier mois renseigné",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "6",
    "frequence": 12,
    "numero": 35
  },
  {
    "id": "EMP6-004",
    "reference": "EMP6-004",
    "terminologie": "Cadre de vie",
    "intitule": "Logements rénovés ou réhabilités",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Logements rénovés ou réhabilités",
    "processus": ["Infrastructures"],
    "gri": "401-2",
    "odd": 8,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "6",
    "frequence": 12,
    "numero": 36
  },
  {
    "id": "EMP6-005",
    "reference": "EMP6-005",
    "terminologie": "Cadre de vie",
    "intitule": "Logements construits",
    "type": "Primaire",
    "unite": "Nombre",
    "definition": "Logements construits",
    "processus": ["Infrastructures"],
    "gri": "401-2",
    "odd": 8,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "2",
    "id_enjeu": "6",
    "frequence": 12,
    "numero": 37
  },
  {
    "id": "INC7-001",
    "reference": "INC7-001",
    "terminologie": "Droits humains",
    "intitule": "Incidents remontés liés au travail des enfants",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Opérations et fournisseurs considérés comme présentant un risque important d'incidents liés au travail des enfants",
    "processus": ["Developpement Durable"],
    "gri": "408-1",
    "odd": 16,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "3",
    "id_enjeu": "7",
    "frequence": 12,
    "numero": 38
  },
  {
    "id": "INC7-002",
    "reference": "INC7-002",
    "terminologie": "Droits humains",
    "intitule":
        "Part des sites de production surveillés par des actions de lutte contre le travail des enfants",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Total des Sites de production surveillés par des actions mises en place contre le travail des enfants / Total des Sites de production",
    "processus": ["Developpement Durable"],
    "gri": "408-1",
    "odd": 16,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "3",
    "id_enjeu": "7",
    "frequence": 12,
    "numero": 39
  },
  {
    "id": "INC7-003",
    "reference": "INC7-003",
    "terminologie": "Droits humains",
    "intitule":
        "Sites de production surveillés par des actions mises en place contre le travail des enfants",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Opérations et fournisseurs surveillés par des actions de lutte contre le travail des enfants",
    "processus": ["Developpement Durable"],
    "gri": "408-1",
    "odd": 16,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "3",
    "id_enjeu": "7",
    "frequence": 12,
    "numero": 40
  },
  {
    "id": "INC7-004",
    "reference": "INC7-004",
    "terminologie": "Droits humains",
    "intitule": "Incidents remontés concernant le travail forcé",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Le travail forcé est une forme d'exploitation par le travail de personnes, sans contrat de travail et soumises aux règles de leur employeur, sans qu'il existe une forme de dialogue social",
    "processus": ["Developpement Durable"],
    "gri": "409-1",
    "odd": 16,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "3",
    "id_enjeu": "7",
    "frequence": 12,
    "numero": 41
  },
  {
    "id": "INC7-005",
    "reference": "INC7-005",
    "terminologie": "Droits humains",
    "intitule":
        "Sites de production surveillés par des actions mises en place contre le travail forcé",
    "type": "Primaire",
    "unite": "Nombre",
    "definition":
        "Opérations et fournisseurs surveillés par des actions de lutte contre le travail forcé",
    "processus": ["Developpement Durable"],
    "gri": "408-1",
    "odd": 16,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "3",
    "id_enjeu": "7",
    "frequence": 12,
    "numero": 42
  },
  {
    "id": "ENV8-001",
    "reference": "ENV8-001",
    "terminologie": "Énergie",
    "intitule": "Dépenses opérationnelles pour l'énergie",
    "type": "Primaire",
    "unite": "KFCFA",
    "definition":
        "Dépenses opérationnelles pour la réduction de la consommation de l'énergie",
    "processus": ["Finances (Contrôle de Gestion / Comptabilité)"],
    "gri": "302-1",
    "odd": "12;13;7",
    "formule": "Somme",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "8",
    "frequence": 12,
    "numero": 43
  },
  {
    "id": "ENV8-002",
    "reference": "ENV8-002",
    "terminologie": "Énergie",
    "intitule": "Part des dépenses opérationnelles pour l'énergie",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Total des Dépenses opérationnelles liées à l'énergie / Total des coûts opérationnels",
    "processus": ["Finances (Contrôle de Gestion / Comptabilité)"],
    "gri": "302-1",
    "odd": "12;13;7",
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "8",
    "frequence": 12,
    "numero": 44
  },
  {
    "id": "ENV9-001",
    "reference": "ENV9-001",
    "terminologie": "Prélèvements eau",
    "intitule": "Prélèvements d'eau dans les eaux douces de surface",
    "type": "Primaire",
    "unite": "m3",
    "definition":
        "Eau qui se trouve naturellement à la surface de la Terre, provenant des zones humides, des calottes glaciaires, des glaciers, des icebergs, des tourbières, des étangs, des lacs, des rivières et des ruisseaux.",
    "processus": ["Usine / Agricole"],
    "gri": "303-3",
    "odd": 6,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "9",
    "frequence": 12,
    "numero": 45
  },
  {
    "id": "ENV9-002",
    "reference": "ENV9-002",
    "terminologie": "Prélèvements eau",
    "intitule": "Prélèvements d'eau apportés par des réseaux municipaux",
    "type": "Primaire",
    "unite": "m3",
    "definition":
        "Les réseaux d'eau tiers sont les fournisseurs d'eau municipaux et les stations d'épuration des eaux usées municipales, les services publics ou privés et les autres organisations impliquées dans la fourniture, le transport, le traitement, l'élimination ou l'utilisation de l'eau et des effluents.",
    "processus": ["Usine / Agricole"],
    "gri": "303-3",
    "odd": 6,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "9",
    "frequence": 12,
    "numero": 46
  },
  {
    "id": "ENV9-003",
    "reference": "ENV9-003",
    "terminologie": "Prélèvements eau",
    "intitule": "Prélèvements d'eau dans les eaux saumâtres de surface",
    "type": "Primaire",
    "unite": "m3",
    "definition": "Prélèvements d'eau dans les eaux saumâtres de surface",
    "processus": ["Usine / Agricole"],
    "gri": "303-3",
    "odd": 6,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "9",
    "frequence": 12,
    "numero": 47
  },
  {
    "id": "ENV9-004",
    "reference": "ENV9-004",
    "terminologie": "Prélèvements eau",
    "intitule": "Prélèvements d'eau dans les eaux de forage",
    "type": "Primaire",
    "unite": "m3",
    "definition": "Prélèvements d'eau dans les eaux de forage",
    "processus": ["Usine / Agricole"],
    "gri": "303-3",
    "odd": 6,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "9",
    "frequence": 12,
    "numero": 48
  },
  {
    "id": "ENV9-006",
    "reference": "ENV9-006",
    "terminologie": "Prélèvements eau",
    "intitule": "Prélèvements dans des zones soumises à un stress hydrique",
    "type": "Primaire",
    "unite": "m3",
    "definition": "Prélèvements dans des zones soumises à un stress hydrique",
    "processus": ["Usine / Agricole"],
    "gri": "303-3",
    "odd": 6,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "9",
    "frequence": 12,
    "numero": 49
  },
  {
    "id": "ENV9-005",
    "reference": "ENV9-005",
    "terminologie": "Prélèvements eau",
    "intitule": "Total des prélèvements d'eau",
    "type": "Calculé",
    "unite": "m3",
    "definition": "Total des prélèvements d'eau",
    "processus": ["Usine / Agricole"],
    "gri": "303-3",
    "odd": 6,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "9",
    "frequence": 12,
    "numero": 50
  },
  {
    "id": "ENV10-001",
    "reference": "ENV10-001",
    "terminologie": "Matières premières",
    "intitule": "Matières premières consommées",
    "type": "Primaire",
    "unite": "Tonnes",
    "definition":
        "Total des matières premières (lubrifiants pour les machines de production, pièces semi-finis, emballages, papiers)",
    "processus": ["Gestion des Stocks / Logistique"],
    "gri": "301-1",
    "odd": 12,
    "formule": "Somme",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "10",
    "frequence": 12,
    "numero": 51
  },
  {
    "id": "ENV10-002",
    "reference": "ENV10-002",
    "terminologie": "Matières premières",
    "intitule": "Part de matières premières par tonnage de production",
    "type": "Calculé",
    "unite": "%",
    "definition":
        "Total des Matières premières consommées / Total du tonnage de production",
    "processus": ["Gestion des Stocks / Logistique"],
    "gri": "301-1",
    "odd": 12,
    "formule": "Calculé",
    "color": "none",
    "id_pilier": "4",
    "id_enjeu": "10",
    "frequence": 12,
    "numero": 52
  }
];
